---
title: "Office Show Analysis"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(tidyverse)
ratings_raw <- readr::read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-03-17/office_ratings.csv")

remove_regex <- "[:punct:]|[:digit:]|parts|part|and|the"

office_ratings <- ratings_raw %>% 
  transmute(episode_name = str_to_lower(title),
            episode_name = str_remove_all(episode_name,remove_regex),
            episode_name=str_trim(episode_name),
            imdb_rating
  )
            

office_info <- schrute::theoffice %>% 
  mutate(
    season = as.numeric(season),
    episode = as.numeric(episode),
    episode_name = str_to_lower(episode_name),
    episode_name= str_remove_all(episode_name,remove_regex),
    episode_name= str_trim(episode_name)
  ) %>% 
  select(season,episode, episode_name,director, writer,character)




```

#How many times character speack per episode

```{r}
characters <- office_info %>% 
  count(episode_name, character) %>% 
  add_count(character, wt=n,name="character_count") %>% 
  filter(character_count >800) %>% 
  select(-character_count) %>% 
  pivot_wider(names_from = character,values_from = n,
              values_fill = list(n=0)
              )

characters
  
```

# Directors and writers who are involvde in each episode.

```{r}
creators <- office_info %>% 
  distinct(episode_name, director, writer) %>% 
  pivot_longer(director:writer,names_to = "role",values_to = "person") %>% 
  separate_rows(person,sep = ";") %>% 
  add_count(person) %>% 
  filter(n>10) %>% 
  distinct(episode_name,person) %>% 
  mutate(person_value = 1) %>% 
  pivot_wider(
    names_from = person,
    values_from = person_value,
    values_fill = list(person_value=0)
  )
  
  
creators
  
```

# Find season and episode number for each episode in one dataset

```{r}

office <- office_info %>% 
  distinct(season,episode,episode_name) %>% 
  inner_join(characters) %>% 
  inner_join(creators) %>% 
  inner_join(office_ratings %>% 
  select(episode_name,imdb_rating)) %>% 
  janitor::clean_names()



```

#EDA on office


```{r}
office %>% ggplot(aes(episode,imdb_rating,fill=as.factor(episode)))+
  geom_boxplot(show.legend = FALSE)

#Rating are higher for episodes later in the season.We can see what else is associated with higher ratings
```

Train a model

```{r}
library(tidymodels)

office_split <- initial_split(office,strata = season)
office_train <- training(office_split)
office_test <- testing(office_split)

office_split

```



```{r}

office_rec <- recipe(imdb_rating ~.,data=office_train) %>% 
  update_role(episode_name,new_role="ID") %>% 
  step_zv(all_numeric(),-all_outcomes()) %>% 
  step_normalize(all_numeric(),-all_outcomes())


office_prep <- office_rec %>% 
  prep(strings_as_factors = FALSE)

```

```{r}
lasso_spec <- linear_reg(penalty = 0.1,mixture =1) %>% 
  set_engine("glmnet")

wf <- workflow() %>% 
  add_recipe(office_rec)


lasso_fit <- wf %>%
  add_model(lasso_spec) %>%
  fit(data = office_train)

lasso_fit %>%
  pull_workflow_fit() %>%
  tidy()


```

```{r}
set.seed(1234)
office_boot <- bootstraps(office_train, strata = season)

tune_spec <- linear_reg(penalty = tune(), mixture = 1) %>%
  set_engine("glmnet")

lambda_grid <- grid_regular(penalty(), levels = 50)

```

#Tuning the grid using workflow object

```{r}
doParallel::registerDoParallel()

set.seed(2020)
lasso_grid <- tune_grid(
  wf %>% add_model(tune_spec),
  resamples = office_boot,
  grid = lambda_grid
)
```

#Results we got.

```{r}
lasso_grid %>%
  collect_metrics()
```


```{r}
lasso_grid %>%
  collect_metrics() %>%
  ggplot(aes(penalty, mean, color = .metric)) +
  geom_errorbar(aes(
    ymin = mean - std_err,
    ymax = mean + std_err
  ),
  alpha = 0.5
  ) +
  geom_line(size = 1.5) +
  facet_wrap(~.metric, scales = "free", nrow = 2) +
  scale_x_log10() +
  theme(legend.position = "none")
```





#Picking the lowest RMSE value.

```{r}
lowest_rmse <- lasso_grid %>%
  select_best("rmse", maximize = FALSE)

final_lasso <- finalize_workflow(
  wf %>% add_model(tune_spec),
  lowest_rmse
)
```


```{r}
library(vip)

final_lasso %>%
  fit(office_train) %>%
  pull_workflow_fit() %>%
  vi(lambda = lowest_rmse$penalty) %>%
  mutate(
    Importance = abs(Importance),
    Variable = fct_reorder(Variable, Importance)
  ) %>%
  ggplot(aes(x = Importance, y = Variable, fill = Sign)) +
  geom_col() +
  scale_x_continuous(expand = c(0, 0)) +
  labs(y = NULL)
```



```{r}
last_fit(
  final_lasso,
  office_split
) %>%
  collect_metrics()
```


